### ISSUE TITLE
About the virtual environment

### ISSUE THREAD

**Issue by ChenyangRan** [Orienfish/ur3-RL#3]
Hello, I'm interested in your work. And since you have refereed to the virtual environment, I want to ask your which simulation you used. I want to learn RL with your code.

**Comment by Orienfish** [comment]
Hi, thanks for your interests and sorry for the late reply.
So we didn't use any formal simulation framework. The virtual environment is built by collecting pictures and the angle of the knob from a microscope. You can check for more details in the paper. 
RL requires a very large amount of trials to train, which is impossible to run in real environment. That's why we have to somehow construct a virtual environment, as real as possible, and train our model there first.
The RL code here is nothing new. It is a basic DQN, similar to the basic ones you can find in a RL introduction course.
Hope this helps!

**Comment by GoogleMike** [comment]
> Hi, thanks for your interests and sorry for the late reply.
> So we didn't use any formal simulation framework. The virtual environment is built by collecting pictures and the angle of the knob from a microscope. You can check for more details in the paper.
> RL requires a very large amount of trials to train, which is impossible to run in real environment. That's why we have to somehow construct a virtual environment, as real as possible, and train our model there first.
> The RL code here is nothing new. It is a basic DQN, similar to the basic ones you can find in a RL introduction course.
> Hope this helps!

**Comment by ChenyangRan** [comment]
Thanks for your replay.  I will read paper carefully.
